import jsPDF from "jspdf";

export interface Transaction {
  id: string;
  createdAt: string;
  amount: string;
  assetCode: string;
  creatorUsername: string;
  senderUsername?: string;
  transactionHash?: string;
  message?: string;
}

export function generateReceipt(tx: Transaction): void {
  const doc = new jsPDF();
  const date = new Date(tx.createdAt).toLocaleDateString();

  doc.setFontSize(22);
  doc.setTextColor(79, 70, 229);
  doc.text("Stellar Tip Jar", 20, 20);

  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text("Tip Receipt", 20, 32);

  doc.setLineWidth(0.5);
  doc.setDrawColor(200, 200, 200);
  doc.line(20, 36, 190, 36);

  doc.setFontSize(11);
  const rows: [string, string][] = [
    ["Transaction ID", tx.id],
    ["Date", date],
    ["Amount", `${tx.amount} ${tx.assetCode}`],
    ["Creator", `@${tx.creatorUsername}`],
    ...(tx.senderUsername ? [["Sender", `@${tx.senderUsername}`] as [string, string]] : []),
    ...(tx.transactionHash ? [["Tx Hash", tx.transactionHash] as [string, string]] : []),
    ...(tx.message ? [["Message", tx.message] as [string, string]] : []),
  ];

  rows.forEach(([label, value], i) => {
    const y = 48 + i * 12;
    doc.setTextColor(100, 100, 100);
    doc.text(`${label}:`, 20, y);
    doc.setTextColor(0, 0, 0);
    doc.text(value, 75, y);
  });

  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by Stellar Tip Jar", 20, 280);

  doc.save(`receipt-${tx.id}.pdf`);
}
